import { AlertCircle, CalendarDays, Clock3, Download, FileText, UserRound } from 'lucide-react';
import type { ReactNode } from 'react';
import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import { ConfirmDeleteDialog } from '@/components/business/common/ConfirmDeleteDialog';
import { ReportProgress } from '@/components/business/reports/ReportProgress';
import { ReportStatusBadge } from '@/components/business/reports/ReportStatusBadge';
import { ReportSummaryCard } from '@/components/business/reports/ReportSummaryCard';
import { ApprovalTimeline } from '@/components/business/workflow/ApprovalTimeline';
import type { ApprovalTimelineItem } from '@/components/business/workflow/ApprovalTimeline';
import { PageContainer } from '@/components/layout/PageContainer';
import { Alert, Card, CardContent, CardDescription, CardHeader, CardTitle, EmptyState, Skeleton } from '@/components/ui';
import { useToast } from '@/providers/ToastProvider';
import { useAuthStore } from '@/stores/auth.store';
import type { WeeklyReport } from '@/types';

import { ReportActionBar } from '../components/ReportActionBar';
import { useCreateReportMutation, useDeleteReportMutation, useReportQuery, useSubmitReportMutation } from '../hooks/useReports';
import {
    createReportPayload,
    formatReportDate,
    getEmployeeName,
    getReportCapabilities,
    getReportFormDefaults,
    getReportProgress,
    getReportTitle,
    hasReportPermission,
    resolveReportAssetUrl,
} from '../utils/report-utils';

const getErrorMessage = (error: unknown): string => (error instanceof Error ? error.message : 'The report could not be loaded.');

const getReportTimestamp = (value: string | null): string => (value ? formatReportDate(value) : 'Not recorded');

const contentSections: Array<{ key: keyof Pick<WeeklyReport, 'achievements' | 'activities' | 'difficulties' | 'executive_summary' | 'next_actions' | 'objectives'>; title: string }> = [
    { key: 'executive_summary', title: 'Executive summary' },
    { key: 'objectives', title: 'Objectives' },
    { key: 'activities', title: 'Activities' },
    { key: 'achievements', title: 'Achievements' },
    { key: 'difficulties', title: 'Difficulties' },
    { key: 'next_actions', title: 'Next actions' },
];

function ReportDetailSkeleton() {
    return (
        <PageContainer description="Loading report details from the Reports API." eyebrow="Reports" title="Report details">
            <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
                <div className="grid gap-6">
                    <Skeleton className="h-36" />
                    <Skeleton className="h-96" />
                </div>
                <div className="grid gap-6">
                    <Skeleton className="h-56" />
                    <Skeleton className="h-64" />
                </div>
            </div>
        </PageContainer>
    );
}

function ReportSection({ children, title }: { children: ReactNode; title: string }) {
    return (
        <section className="rounded-2xl border bg-background p-4">
            <h3 className="text-sm font-semibold text-foreground">{title}</h3>
            <div className="mt-3 whitespace-pre-line text-sm leading-7 text-muted-foreground">{children}</div>
        </section>
    );
}

function buildTimeline(report: WeeklyReport): ApprovalTimelineItem[] {
    const items: ApprovalTimelineItem[] = [
        {
            actor: getEmployeeName(report),
            description: 'The weekly report was created in ReportFlow.',
            id: 'created',
            status: 'approved',
            timestamp: getReportTimestamp(report.created_at),
            title: 'Created',
        },
    ];

    if (report.submitted_at) {
        items.push({
            actor: getEmployeeName(report),
            description: 'The report entered the approval workflow.',
            id: 'submitted',
            status: report.status.value === 'submitted' ? 'current' : 'approved',
            timestamp: getReportTimestamp(report.submitted_at),
            title: 'Submitted',
        });
    }

    if (report.validated_at) {
        items.push({
            actor: report.validator ?? 'Manager',
            description: 'The report was validated by the approval workflow.',
            id: 'validated',
            status: report.status.value === 'manager_approved' ? 'current' : 'approved',
            timestamp: getReportTimestamp(report.validated_at),
            title: 'Validated',
        });
    }

    if (report.generated_at) {
        items.push({
            actor: report.validator ?? 'ReportFlow',
            description: 'The PowerPoint export was generated by the backend.',
            id: 'generated',
            status: report.status.value === 'generated' ? 'current' : 'approved',
            timestamp: getReportTimestamp(report.generated_at),
            title: 'Generated',
        });
    }

    if (report.rejected_at) {
        items.push({
            actor: report.rejector ?? 'Reviewer',
            description: report.rejection_reason ?? 'The report was rejected by the workflow.',
            id: 'rejected',
            status: 'rejected',
            timestamp: getReportTimestamp(report.rejected_at),
            title: 'Rejected',
        });
    }

    if (!report.submitted_at && report.status.value === 'draft') {
        items.push({
            description: 'Submit the report when it is ready for review.',
            id: 'draft',
            status: 'current',
            title: 'Draft in progress',
        });
    }

    return items;
}

export function ReportDetailPage() {
    const navigate = useNavigate();
    const { id } = useParams();
    const reportId = Number(id);
    const user = useAuthStore((state) => state.user);
    const { notify } = useToast();
    const [deleteOpen, setDeleteOpen] = useState(false);
    const reportQuery = useReportQuery(Number.isFinite(reportId) ? reportId : 0);
    const deleteReport = useDeleteReportMutation();
    const duplicateReport = useCreateReportMutation();
    const submitReport = useSubmitReportMutation();

    const report = reportQuery.data?.data;
    const capabilities = report ? getReportCapabilities(report, user) : undefined;
    const exportUrl = report?.pptx_file ? resolveReportAssetUrl(report.pptx_file) : undefined;

    const timeline = useMemo(() => (report ? buildTimeline(report) : []), [report]);

    const handleDelete = () => {
        if (!report) {
            return;
        }

        deleteReport.mutate(report.id, {
            onSuccess: () => {
                notify({ intent: 'success', title: 'Report deleted', description: 'The report was removed successfully.' });
                navigate('/reports');
            },
            onError: (error) => {
                notify({ intent: 'error', title: 'Delete failed', description: getErrorMessage(error) });
            },
        });
    };

    const handleDuplicate = () => {
        if (!report) {
            return;
        }

        duplicateReport.mutate(createReportPayload(getReportFormDefaults(report)), {
            onSuccess: (response) => {
                notify({ intent: 'success', title: 'Report duplicated', description: 'A draft copy was created.' });
                navigate(`/reports/${response.data.id}/edit`);
            },
            onError: (error) => {
                notify({ intent: 'error', title: 'Duplicate failed', description: getErrorMessage(error) });
            },
        });
    };

    const handleSubmit = () => {
        if (!report) {
            return;
        }

        submitReport.mutate(report.id, {
            onSuccess: () => {
                notify({ intent: 'success', title: 'Report submitted', description: 'The report is now in the approval workflow.' });
            },
            onError: (error) => {
                notify({ intent: 'error', title: 'Submit failed', description: getErrorMessage(error) });
            },
        });
    };

    if (!Number.isFinite(reportId) || reportId <= 0) {
        return (
            <PageContainer description="The requested report identifier is invalid." eyebrow="Reports" title="Report not found">
                <EmptyState action={{ label: 'Back to reports', onClick: () => navigate('/reports') }} icon={<FileText aria-hidden="true" className="size-10" />} title="Invalid report" description="Open an existing report from the reports list." />
            </PageContainer>
        );
    }

    if (!hasReportPermission(user, 'reports.view')) {
        return (
            <PageContainer description="Your account does not currently expose report viewing permission." eyebrow="Reports" title="No report access">
                <EmptyState action={{ label: 'Go to dashboard', onClick: () => navigate('/dashboard') }} icon={<AlertCircle aria-hidden="true" className="size-10" />} title="Permission required" description="Report details are only available to users with reports.view permission." />
            </PageContainer>
        );
    }

    if (reportQuery.isLoading) {
        return <ReportDetailSkeleton />;
    }

    if (reportQuery.isError) {
        return (
            <PageContainer description="The Reports API returned an error." eyebrow="Reports" title="Report details">
                <Alert intent="danger" title="Unable to load report" description={getErrorMessage(reportQuery.error)} />
                <EmptyState action={{ label: 'Back to reports', onClick: () => navigate('/reports') }} title="Report unavailable" description="Try again later or open another report from the list." />
            </PageContainer>
        );
    }

    if (!report || !capabilities) {
        return (
            <PageContainer description="No report was returned by the Reports API." eyebrow="Reports" title="Report not found">
                <EmptyState action={{ label: 'Back to reports', onClick: () => navigate('/reports') }} icon={<FileText aria-hidden="true" className="size-10" />} title="Report not found" description="The report may have been deleted or is no longer available." />
            </PageContainer>
        );
    }

    return (
        <PageContainer
            actions={
                <ReportActionBar
                    capabilities={capabilities}
                    exportUrl={exportUrl}
                    onDelete={() => setDeleteOpen(true)}
                    onDuplicate={handleDuplicate}
                    onEdit={() => navigate(`/reports/${report.id}/edit`)}
                    onPrint={() => window.print()}
                    onSubmit={handleSubmit}
                    pendingAction={deleteReport.isPending ? 'delete' : duplicateReport.isPending ? 'duplicate' : submitReport.isPending ? 'submit' : null}
                />
            }
            description={`${report.department} · ${report.week} · ${getEmployeeName(report)}`}
            eyebrow="Reports"
            title={getReportTitle(report)}
        >
            <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
                <div className="grid gap-6">
                    <ReportSummaryCard
                        title="Report overview"
                        items={[
                            { label: 'Status', value: <ReportStatusBadge label={report.status.label} status={report.status.value} /> },
                            { label: 'Department', value: report.department },
                            { label: 'Week', value: report.week },
                            { label: 'Author', value: getEmployeeName(report) },
                        ]}
                    />

                    <Card>
                        <CardHeader>
                            <CardTitle>Report content</CardTitle>
                            <CardDescription>Complete weekly report content from the Reports API.</CardDescription>
                        </CardHeader>
                        <CardContent className="grid gap-4">
                            {contentSections.map((section) => (
                                <ReportSection key={section.key} title={section.title}>
                                    {report[section.key] || 'Not provided'}
                                </ReportSection>
                            ))}
                        </CardContent>
                    </Card>
                </div>

                <aside className="grid content-start gap-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Workflow</CardTitle>
                            <CardDescription>Current approval progress and timeline.</CardDescription>
                        </CardHeader>
                        <CardContent className="grid gap-5">
                            <ReportProgress value={getReportProgress(report.status.value)} />
                            <ApprovalTimeline items={timeline} />
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>Metadata</CardTitle>
                            <CardDescription>System dates and ownership.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <dl className="grid gap-3 text-sm">
                                <div className="rounded-xl bg-muted/60 p-3">
                                    <dt className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground"><CalendarDays aria-hidden="true" className="size-4" /> Created</dt>
                                    <dd className="mt-1 font-medium text-foreground">{getReportTimestamp(report.created_at)}</dd>
                                </div>
                                <div className="rounded-xl bg-muted/60 p-3">
                                    <dt className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground"><Clock3 aria-hidden="true" className="size-4" /> Last update</dt>
                                    <dd className="mt-1 font-medium text-foreground">{getReportTimestamp(report.updated_at)}</dd>
                                </div>
                                <div className="rounded-xl bg-muted/60 p-3">
                                    <dt className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground"><UserRound aria-hidden="true" className="size-4" /> Author</dt>
                                    <dd className="mt-1 font-medium text-foreground">{getEmployeeName(report)}</dd>
                                </div>
                                {report.pptx_file && (
                                    <div className="rounded-xl bg-muted/60 p-3">
                                        <dt className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground"><Download aria-hidden="true" className="size-4" /> Export</dt>
                                        <dd className="mt-2">
                                            <a className="text-sm font-medium text-primary underline-offset-4 hover:underline" href={exportUrl} rel="noreferrer" target="_blank">Download PowerPoint</a>
                                        </dd>
                                    </div>
                                )}
                            </dl>
                        </CardContent>
                    </Card>
                </aside>
            </div>

            <ConfirmDeleteDialog
                description="This report will be permanently deleted. This action cannot be undone."
                onConfirm={handleDelete}
                onOpenChange={setDeleteOpen}
                open={deleteOpen}
                resourceName={getReportTitle(report)}
                title="Delete report"
            />
        </PageContainer>
    );
}
