import { zodResolver } from '@hookform/resolvers/zod';
import { AlertCircle, RefreshCw, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';

import { Alert, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Checkbox, Input, Select, Textarea } from '@/components/ui';
import { getAiErrorHint, getErrorMessage } from '@/lib/errors';
import { useToast } from '@/providers/ToastProvider';
import { useAuthStore } from '@/stores/auth.store';
import type { AiAction, AiGeneration, AiProvider, AiSection, WeeklyReport } from '@/types';

import { useAiGenerationMutation, useAiProvidersQuery } from '../hooks/useAi';
import { aiGenerationFormSchema } from '../schemas/ai.schema';
import type { AiGenerationFormValues } from '../schemas/ai.schema';
import { aiActionMeta, aiLocaleOptions, aiSectionOptions, canRequestWorkflowRecommendation, getAiActionDescription, getAvailableReportAssistantActions } from '../utils/ai-utils';
import { AiResultCard } from './AiResultCard';

export type AiReportActionPanelProps = {
    actions?: readonly AiAction[];
    defaultAction?: AiAction;
    description?: string;
    report?: WeeklyReport;
    title?: string;
};

const toSelectOptions = (actions: readonly AiAction[]) =>
    actions.map((action) => ({
        label: aiActionMeta[action].label,
        value: action,
    }));

const getProviderLabel = (providers: readonly AiProvider[], providerName: string | null | undefined): string | undefined =>
    providers.find((provider) => provider.name === providerName)?.label ?? providerName ?? undefined;

const getActiveProvider = (providers: readonly AiProvider[]): AiProvider | undefined =>
    providers.find((provider) => provider.active) ?? providers.find((provider) => provider.configured) ?? providers[0];

export function AiReportActionPanel({
    actions,
    defaultAction = 'writing_improvement',
    description = 'Run AI assistance against an existing weekly report. Results are generated by the backend AI API.',
    report,
    title = 'Report Assistant',
}: AiReportActionPanelProps) {
    const user = useAuthStore((state) => state.user);
    const { notify } = useToast();
    const [generation, setGeneration] = useState<AiGeneration | null>(null);
    const availableActions = useMemo(() => actions ?? getAvailableReportAssistantActions(user), [actions, user]);
    const actionOptions = useMemo(() => toSelectOptions(availableActions), [availableActions]);
    const generationMutation = useAiGenerationMutation();
    const providersQuery = useAiProvidersQuery();
    const providers = providersQuery.data?.data ?? [];
    const activeProvider = getActiveProvider(providers);
    const activeProviderLabel = activeProvider?.label;
    const resultProviderLabel = getProviderLabel(providers, generation?.provider);
    const fallbackUsed = Boolean(generation && activeProvider && generation.provider !== activeProvider.name);

    const {
        formState: { errors },
        handleSubmit,
        register,
        reset,
        watch,
    } = useForm<AiGenerationFormValues>({
        defaultValues: {
            action: availableActions.includes(defaultAction) ? defaultAction : availableActions[0],
            instructions: '',
            locale: 'fr',
            persist: false,
            report_id: report?.id ?? 0,
            section: '',
            text: '',
        },
        resolver: zodResolver(aiGenerationFormSchema),
    });

    const selectedAction = watch('action');
    const canPersist = selectedAction === 'executive_summary';
    const workflowRestricted = selectedAction === 'workflow_recommendation' && !canRequestWorkflowRecommendation(user);

    useEffect(() => {
        reset({
            action: availableActions.includes(defaultAction) ? defaultAction : availableActions[0],
            instructions: '',
            locale: 'fr',
            persist: false,
            report_id: report?.id ?? 0,
            section: '',
            text: '',
        });
    }, [availableActions, defaultAction, report?.id, reset]);

    const submitForm = handleSubmit((values) => {
        setGeneration(null);
        generationMutation.mutate(
            {
                action: values.action,
                instructions: values.instructions || undefined,
                locale: values.locale,
                persist: values.action === 'executive_summary' ? values.persist : false,
                reportId: values.report_id,
                section: values.section ? (values.section as AiSection) : undefined,
                text: values.text || undefined,
            },
            {
                onError: (error) => {
                    notify({ intent: 'error', title: 'AI generation failed', description: `${getErrorMessage(error, 'AI generation failed.')} ${getAiErrorHint(error)}` });
                },
                onSuccess: (response) => {
                    const responseProviderLabel = getProviderLabel(providers, response.data.provider) ?? response.data.provider;
                    const usedFallback = Boolean(activeProvider && response.data.provider !== activeProvider.name);

                    setGeneration(response.data);
                    notify({
                        intent: 'success',
                        title: usedFallback ? 'AI generation complete via fallback' : 'AI generation complete',
                        description: `${responseProviderLabel}${response.data.model ? ` ? ${response.data.model}` : ''}`,
                    });
                },
            },
        );
    });

    return (
        <div className="grid gap-5">
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Sparkles aria-hidden="true" className="size-5 text-primary" />
                        {title}
                    </CardTitle>
                    <CardDescription>{description}</CardDescription>
                </CardHeader>
                <CardContent>
                    <form className="grid gap-4" onSubmit={submitForm}>
                        {providersQuery.isError ? (
                            <Alert
                                description="Provider metadata could not be loaded. Generation can still use the backend default when configured."
                                icon={<AlertCircle aria-hidden="true" className="size-5" />}
                                intent="warning"
                                title="AI provider status unavailable"
                            />
                        ) : (
                            <Alert
                                description={
                                    activeProvider
                                        ? `Model: ${activeProvider.default_model ?? 'Backend default'} ? ${activeProvider.configured ? 'Configured' : 'Unavailable'}`
                                        : providersQuery.isLoading
                                          ? 'Loading provider metadata from the backend.'
                                          : 'No provider metadata was returned by the backend.'
                                }
                                intent={activeProvider?.configured ? 'info' : 'warning'}
                                title={`Active provider: ${activeProviderLabel ?? 'Not reported'}`}
                            />
                        )}

                        {generationMutation.isError && (
                            <div className="grid gap-3">
                                <Alert
                                    description={`${getErrorMessage(generationMutation.error, 'AI generation failed.')} ${getAiErrorHint(generationMutation.error)}`}
                                    icon={<AlertCircle aria-hidden="true" className="size-5" />}
                                    intent="danger"
                                    title="Unable to generate AI result"
                                />
                                <div>
                                    <Button
                                        leftIcon={<RefreshCw aria-hidden="true" className="size-4" />}
                                        loading={generationMutation.isPending}
                                        onClick={() => void submitForm()}
                                        variant="outline"
                                    >
                                        Retry generation
                                    </Button>
                                </div>
                            </div>
                        )}

                        <div className="grid gap-4 md:grid-cols-2">
                            <Input
                                error={errors.report_id?.message}
                                helperText={report ? `${report.department} ? ${report.week}` : 'Use an existing report ID.'}
                                label="Report ID"
                                min={1}
                                readOnly={Boolean(report)}
                                type="number"
                                {...register('report_id', { valueAsNumber: true })}
                            />
                            <Select error={errors.action?.message} label="AI action" options={actionOptions} {...register('action')} />
                        </div>

                        <div className="grid gap-4 md:grid-cols-2">
                            <Select error={errors.section?.message} label="Report section" options={aiSectionOptions} {...register('section')} />
                            <Select error={errors.locale?.message} label="Output language" options={aiLocaleOptions} {...register('locale')} />
                        </div>

                        <Textarea
                            error={errors.text?.message}
                            helperText="Optional. Paste selected report text when you want a focused response."
                            label="Selected text"
                            rows={4}
                            {...register('text')}
                        />
                        <Textarea
                            error={errors.instructions?.message}
                            helperText={getAiActionDescription(selectedAction)}
                            label="Additional instructions"
                            rows={3}
                            {...register('instructions')}
                        />

                        {canPersist && (
                            <Checkbox
                                description="The backend will save the generated executive summary on the report when permitted."
                                label="Persist generated executive summary"
                                {...register('persist')}
                            />
                        )}

                        {workflowRestricted && (
                            <Alert
                                intent="warning"
                                title="Workflow recommendation restricted"
                                description="The backend allows workflow recommendations only for managers and super-admins."
                            />
                        )}

                        <div className="flex justify-end">
                            <Button
                                disabled={workflowRestricted}
                                leftIcon={<Sparkles aria-hidden="true" className="size-4" />}
                                loading={generationMutation.isPending}
                                type="submit"
                            >
                                Generate
                            </Button>
                        </div>
                    </form>
                </CardContent>
            </Card>

            <AiResultCard
                activeProviderLabel={activeProviderLabel}
                autoFocus
                fallbackUsed={fallbackUsed}
                generation={generation}
                loading={generationMutation.isPending}
                providerLabel={resultProviderLabel}
            />
        </div>
    );
}
